- .github/workflows/docker-beta-image.yml
Add beta branch and github action flow for beta phase
> deploy: beta phase

- apps/api/src/domains/history/history.service.ts
This reverts commit 3290a12c1978b9529e3cbd81507c65e6bb4e1419.
> Revert "fix: creating history with separate transaction (#12)"

- apps/api/src/domains/feedback/feedback.service.ts
- apps/web/src/components/etc/TableSearchInput/TableSearchInput.tsx
- apps/web/src/components/etc/TableSearchInput/TableSearchInputPopover.tsx
- apps/web/src/components/etc/TableSearchInput/table-search-input.service.ts
- apps/web/src/containers/tables/FeedbackTable/FeedbackTable.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTableBar/FeedbackTableBar.tsx
- apps/web/src/containers/tables/IssueTable/IssueTable.tsx
- apps/web/src/types/date-range.type.ts
- apps/web/src/utils/remove-empty-value-in-object.ts
- yarn.lock
- issue is duplicated in search filter
- issue search is fixed
> fix: issue in table search filter

- apps/api/README.md
- apps/api/src/domains/channel/field/field.service.ts
- apps/api/src/domains/migration/migration.service.ts
save timezone with datetime in opensearch
> fix: datetime with timezone

- apps/api/src/configs/modules/typeorm-config/migrations/1692690482919-issue-name-unique.ts
- apps/api/src/domains/project/issue/issue.entity.ts
The name of issue should be unique with the project id, not itself.
> fix: issue unique on name and project_id

- apps/api/README.md
- apps/api/src/configs/mysql.config.ts
- apps/api/src/domains/feedback/feedback.mysql.service.ts
- apps/api/src/domains/project/issue/issue.service.ts
- apps/api/src/domains/user/user.service.ts
Convert timezone when searching on mysql created columns (e.g. createdAt, updatedAt)
> fix: convert timezone on mysql created columns

- apps/api/README.md
- apps/api/src/configs/modules/typeorm-config/typeorm-config.service.ts
- apps/api/src/configs/mysql.config.ts
- apps/api/src/domains/feedback/feedback.mysql.service.ts
- apps/api/src/domains/project/issue/issue.service.ts
- apps/api/src/domains/user/user.service.ts
- apps/api/src/utils/test-utils.ts
- turbo.json
> fix: no timezone option

- apps/api/src/domains/feedback/dtos/create-feedback.dto.ts
- apps/api/src/domains/feedback/feedback.controller.ts
- apps/api/src/domains/feedback/feedback.service.spec.ts
- apps/api/src/domains/feedback/feedback.service.ts
- apps/api/src/domains/project/issue/issue.service.ts
- apps/api/src/utils/test-utils.ts
- if the feedback has existent issues, they just added to the feedback
- if the feedback has nonexistent issues, they will be created and added
> feat: create issues on creating a feedback

- .github/workflows/test-on-pr.yml
- .husky/pre-commit
- README.md
- apps/api/package.json
- apps/api/src/common/repositories/opensearch.repository.spec.ts
- apps/api/src/domains/channel/channel/channel.controller.spec.ts
- apps/api/src/domains/channel/option/option.controller.spec.ts
- apps/api/src/domains/feedback/feedback.controller.spec.ts
- apps/api/src/domains/project/api-key/api-key.controller.spec.ts
- apps/api/src/domains/project/issue-tracker/issue-tracker.controller.spec.ts
- apps/api/src/domains/project/issue/issue.controller.spec.ts
- apps/api/src/domains/project/project/project.controller.spec.ts
- apps/api/src/domains/project/role/role.controller.spec.ts
- apps/api/src/shared/mailing/email-verification-mailing.service.spec.ts
- apps/api/src/shared/mailing/reset-password-mailing.service.spec.ts
- apps/api/src/shared/mailing/user-invitation-mailing.service.spec.ts
- apps/api/src/utils/test-utils.ts
- apps/web/package.json
- package.json
- turbo.json
- yarn.lock
- run lint/format on commit (typo on commit message...)
- run test on PR
> some features on CI

- apps/api/src/domains/history/history.service.ts
I think we should not handle errors on saving history because it is log data.
> fix: no error handling on saving history

- apps/api/.env.example
- apps/api/README.md
- apps/api/src/configs/smtp.config.ts
- apps/api/src/domains/project/project/project.service.spec.ts
- apps/api/src/domains/tenant/dtos/responses/get-tenant-response.dto.ts
- apps/api/src/domains/tenant/tenant.entity.ts
- apps/api/src/domains/tenant/tenant.service.spec.ts
- apps/api/src/domains/tenant/tenant.service.ts
- docker-compose.infra.yml
- turbo.json
> feat: no smtp mode

- apps/api/src/domains/feedback/feedback.mysql.service.ts
- apps/api/src/domains/feedback/feedback.service.ts
Update updatedAt of feedback when issue is added or removed from the feedback
> fix: update feedback updatedAt on issue modification

- .dockerignore
- README.md
- apps/api/Dockerfile
- apps/web/Dockerfile
- apps/web/README.md
- apps/web/src/pages/_app.tsx
- docker-compose.yml
- package.json
- packages/ufb-tailwind/package.json
- packages/ufb-ui/package.json
- turbo.json
- update Dockerfile and turbo.json to use turborepo
> feat: turborepo pipeline 

- apps/web/next.config.js
- apps/web/public/locales/en/common.json
- apps/web/public/locales/ja/common.json
- apps/web/public/locales/ko/common.json
- apps/web/src/components/etc/CheckedTableHead/CheckedTableHead.tsx
- apps/web/src/components/etc/DateRangePicker/DateRangePicker.tsx
- apps/web/src/components/etc/ShareButton/ShareButton.tsx
- apps/web/src/components/etc/TableResizer/TableResizer.tsx
- apps/web/src/components/etc/TableResizer/index.ts
- apps/web/src/components/etc/TableSearchInput/TableSearchInput.tsx
- apps/web/src/components/etc/TableSearchInput/table-search-input.service.ts
- apps/web/src/components/etc/index.ts
- apps/web/src/components/layouts/Header/HeaderName.tsx
- apps/web/src/components/layouts/SideNav/SideNav.tsx
- apps/web/src/components/templates/MainTemplate/MainTemplate.tsx
- apps/web/src/containers/tables/FeedbackTable/ColumnSettingPopover/ColumnSettingPopover.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTable.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTableBar/FeedbackTableBar.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTableRow/FeedbackTableRow.tsx
- apps/web/src/containers/tables/FeedbackTable/feedback-table.context.tsx
- apps/web/src/containers/tables/IssueTable/IssueTable.tsx
- apps/web/src/hooks/useQueryParamsState.ts
- packages/ufb-ui/src/Badge/Badge.tsx
- remove `management` word
- change button location in feedback table head
- fix date selection in date range picker
- add createdAt to share link
- add query string in feedback and issue table page
> fix: web issues

- apps/api/src/domains/channel/field/field.mysql.service.ts
- apps/api/src/domains/feedback/feedback.service.ts
- As fields will be created in order (especially DEFAULT fields first), I removed ordering logic in download.
- Fix bugs on getting fields in order.
> fix: field order

- apps/web/public/locales/en/common.json
- apps/web/public/locales/ja/common.json
- apps/web/public/locales/ko/common.json
- apps/web/src/containers/tables/FeedbackTable/FeedbackDetail/FeedbackDetailCell.tsx
> impl: i18n

- apps/api/src/domains/channel/field/field.mysql.service.ts
- apps/api/src/domains/channel/field/field.service.ts
- apps/api/src/domains/feedback/dtos/generate-excel.dto.ts
- apps/api/src/domains/feedback/dtos/requests/export-feedbacks-request.dto.ts
- apps/api/src/domains/feedback/feedback.controller.spec.ts
- apps/api/src/domains/feedback/feedback.controller.ts
- apps/api/src/domains/feedback/feedback.service.ts
export xlsx/csv with specific fields
> impl: excel download with specific fields

- apps/web/public/locales/en/common.json
- apps/web/public/locales/ja/common.json
- apps/web/src/containers/create-project/InputIssueTracker.tsx
- timeoffset 
- register-member i18n
> fix: web minor bug

- apps/api/src/domains/channel/channel/dtos/requests/create-channel-request.dto.ts
- apps/api/src/domains/channel/channel/dtos/requests/update-channel-request.dto.ts
- apps/api/src/domains/channel/option/dtos/requests/create-option-request.dto.ts
- apps/api/src/domains/project/issue/dtos/requests/create-issue-request.dto.ts
- apps/api/src/domains/project/issue/dtos/requests/update-issue-request.dto.ts
- apps/api/src/domains/project/project/dtos/requests/create-project-request.dto.ts
- apps/api/src/domains/tenant/dtos/requests/setup-tenant-request.dto.ts
> fix: max length of name and description

- apps/api/package.json
- apps/api/src/common/entities/common.entity.ts
- apps/api/src/domains/auth/auth.controller.spec.ts
- apps/api/src/domains/auth/auth.service.ts
- apps/api/src/domains/feedback/feedback.controller.ts
- apps/api/src/domains/feedback/feedback.mysql.service.ts
- apps/api/src/domains/feedback/feedback.os.service.ts
- apps/api/src/domains/feedback/feedback.service.ts
- apps/api/src/domains/migration/migration.service.ts
- apps/api/src/domains/project/api-key/api-key.service.ts
- apps/api/src/domains/statistics/feedback-issue/feedback-issue-statistics.service.ts
- apps/api/src/domains/statistics/feedback/feedback-statistics.service.ts
- apps/api/src/domains/statistics/issue/issue-statistics.service.ts
- apps/api/src/shared/code/code.service.spec.ts
- apps/api/src/shared/code/code.service.ts
- apps/api/test/user.e2e-spec.ts
- change date library (dayjs -> luxon)
- fix bug on statistics date value
> refactor: dayjs -> luxon

- apps/api/src/domains/channel/channel/channel.mysql.service.ts
- apps/api/src/domains/channel/channel/dtos/requests/update-channel-request.dto.ts
- set image config optional on updating channel
- can use same channel name between projects on updating channel
> fix: channel update bug

- apps/web/public/locales/en/common.json
- apps/web/public/locales/ja/common.json
- apps/web/public/locales/ko/common.json
- apps/web/src/components/charts/LineChart.tsx
- apps/web/src/components/layouts/Header/LocaleSelectBox.tsx
- apps/web/src/containers/dashboard/FeedbackLineChart.tsx
- apps/web/src/containers/dashboard/IssueFeedbackLineChart.tsx
- apps/web/src/containers/dashboard/IssueLineChart.tsx
> fix: minor bugs in dashboard page

- apps/web/src/components/etc/TableSearchInput/TableSearchInput.tsx
- apps/web/src/components/etc/TableSearchInput/table-search-input.service.ts
- apps/web/src/containers/tables/FeedbackTable/FeedbackDetail/FeedbackDetail.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTable.tsx
- apps/web/src/containers/tables/IssueTable/IssueTable.tsx
- fix: display boolean format in feedback detail
- fix: issue search query
- fix: feedback query
> fix: web minor bugs

- apps/api/src/domains/statistics/feedback-issue/feedback-issue-statistics.service.ts
- apps/api/src/domains/statistics/feedback/feedback-statistics.service.ts
- apps/api/src/domains/statistics/issue/issue-statistics.service.ts
- split cron time for preventing job crowded in same time
- calculate for 365 days data every cron job
> impl: refresh statistics data on cron schedule

- apps/api/src/domains/feedback/feedback.mysql.service.ts
- apps/api/src/domains/project/issue/issue.module.ts
- apps/api/src/domains/project/issue/issue.service.ts
- feedback count decreases on feedback deletion
- bug fix on updating null feedback additional data
- calculate feedback count by issues every day in case of errors
> fix: feedback count in issue

- apps/api/src/domains/feedback/feedback.mysql.service.ts
- apps/api/src/domains/feedback/feedback.service.spec.ts
- apps/api/src/domains/feedback/feedback.service.ts
- apps/api/src/domains/project/issue/issue.service.spec.ts
- apps/api/src/domains/project/issue/issue.service.ts
- apps/api/src/domains/statistics/feedback-issue/feedback-issue-statistics.service.spec.ts
- apps/api/src/domains/statistics/feedback-issue/feedback-issue-statistics.service.ts
- apps/api/src/domains/statistics/feedback/feedback-statistics.service.spec.ts
- apps/api/src/domains/statistics/feedback/feedback-statistics.service.ts
- apps/api/src/domains/statistics/issue/issue-statistics.service.spec.ts
- apps/api/src/domains/statistics/issue/issue-statistics.service.ts
- fix bug on updating count with timezone
- update statistics data on real time
> fix: dashboard data api

- apps/web/src/pages/auth/oauth-callback.tsx
- apps/web/src/pages/main/project/[projectId]/dashboard.tsx
- apps/web/src/pages/main/project/[projectId]/feedback.tsx
- apps/web/src/pages/main/project/[projectId]/issue.tsx
- apps/web/src/pages/main/project/[projectId]/setting.tsx
- remove redirecting to not-permission page because of bugs
> fix: remove redirecting to not-permission page

- apps/web/src/containers/dashboard/TodayFeedbackCard.tsx
- apps/web/src/containers/dashboard/TotalFeedbackCard.tsx
- apps/web/src/containers/dashboard/TotalIssueCard.tsx
- [fix: change date range in total feedback and issue card](https://github.com/line/abc-user-feedback/commit/221174dbcd6f5cd3dd37f0f6dc8c4960df34331a)
> release: 4.2405.36

- apps/web/package.json
- apps/web/src/components/etc/DashboardTable/DashboardTable.tsx
- apps/web/src/containers/dashboard/IssueRank.tsx
- yarn.lock
- I found an error when changing the limit of "top issue" on the dashboard page. This error occurred only when chrome translation was executed.
- So. i fixed this error by adding p tag to text
> fix: add p tag in top issue rank component

- apps/web/src/containers/tables/IssueTable/IssueSettingPopover/IssueSettingPopover.tsx
- apps/web/src/containers/tables/IssueTable/IssueTabelSelectBox/IssueTabelSelectBox.tsx
- apps/web/src/containers/tables/IssueTable/IssueTable.tsx
- apps/web/src/hooks/index.ts
- apps/web/src/hooks/useIssueCount.ts
- Issue table queries apply to all components in issue page
- Issue table queries refetch when issue is modified
> fix: issue table query in issue page

- apps/api/package.json
- apps/api/src/app.module.ts
- apps/api/src/configs/modules/typeorm-config/migrations/1707356935078-deprecate-boolean-field.ts
- apps/api/src/configs/modules/typeorm-config/migrations/1707979877289-code-verification-try-count.ts
- apps/api/src/shared/code/code.entity.ts
- apps/api/src/shared/code/code.service.spec.ts
- apps/api/src/shared/code/code.service.ts
- apps/api/src/test-utils/providers/code.service.providers.ts
- yarn.lock
- verification try count limit: 5
- generate code with secure random
> fix: verify code with secure way

- apps/web/src/components/etc/DateRangePicker/DateRangePicker.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTable.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTableBar/FeedbackTableBar.tsx
- apps/web/src/containers/tables/FeedbackTable/feedback-table.context.tsx
- apps/web/src/containers/tables/IssueTable/IssueTabelSelectBox/IssueTabelSelectBox.tsx
- apps/web/src/containers/tables/IssueTable/IssueTable.tsx
- apps/web/src/hooks/useQueryParamsState.ts
- apps/web/src/pages/main/project/[projectId]/dashboard.tsx
- fix a bug that users can input the invalid date through url
- fix a bug that users cannot search number format in feedback page
- fix yesterday range in date picker
> fix: useQueryParamsState

- apps/api/src/domains/admin/auth/auth.service.ts
- apps/api/src/domains/admin/user/user-password.service.ts
- apps/api/src/shared/code/code.service.spec.ts
- apps/api/src/shared/code/code.service.ts
- apps/api/src/test-utils/providers/code.service.providers.ts
- reset try count on new code request
- refactor code service
> fix: reset try count on new code request

- apps/api/src/domains/admin/user/user-password.service.spec.ts
- apps/api/src/shared/code/code.service.spec.ts
- apps/api/src/shared/code/code.service.ts
- Lock a code row for update try count to prevent brute-force attack
> fix: lock code row for update

- GUIDE.md
- apps/api/src/domains/admin/project/webhook/webhook.listener.ts
- fix webhook sending data format
- webhook guide document
> fix: webhook sending data format

- apps/e2e/global.setup.ts
- apps/e2e/scenarios/no-database-seed/create-project.spec.ts
- apps/e2e/scenarios/with-database-seed/create-channel.spec.ts
- apps/e2e/scenarios/with-database-seed/create-feedback.spec.ts
- apps/web/public/locales/de/common.json
- apps/web/public/locales/en/common.json
- apps/web/public/locales/zh/common.json
- refine awkward expressions in English
- add webhook text for German and Chinese
> fix: language

- apps/web/src/containers/setting-menu/FieldSetting/FieldSettingPopover.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackDetail/FeedbackDetailCell.tsx
- packages/ufb-ui/src/Tooltip/Tooltip.tsx
- remove portal in tooltip
- add whitespace-pre-lin in feedback detail
- disable key in field setting
> fix: tooltip, feedback space and newline and disable key in field setting

- apps/web/src/components/etc/ExpandableText/ExpandableText.tsx
- apps/web/src/containers/setting-menu/FieldSetting/FieldSettingPopover.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackCell/FeedbackCell.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackDetail/FeedbackDetailCell.tsx
- apps/web/src/containers/tables/FeedbackTable/FeedbackTable.tsx
- apps/web/src/containers/tables/IssueTable/IssueTable.tsx
- packages/ufb-ui/src/Tooltip/Tooltip.tsx
- change feedback cell wrap
- disable key in field setting
- fix tooltip bugs
- apply multi select option order in feedback table
- fix feedback table search bugs
> fix web minor bugs

- apps/api/src/configs/smtp.config.ts
> fix: smtp config bug

- apps/web/public/locales/de/common.json
Hi!
I have seen that you have recently added German translations. (#216)
As a native speaker, I thought I'd have a quick look and correct it to the best of my knowledge and belief.
Thank you for your great work :)
references #44
> improved german translation

- apps/api/src/common/enums/field-property.enum.ts
- apps/api/src/common/enums/index.ts
- apps/api/src/configs/modules/typeorm-config/migrations/1713716840764-deprecate-field-format.ts
- apps/api/src/domains/admin/channel/channel/dtos/requests/create-channel-request.dto.ts
- apps/api/src/domains/admin/channel/field/dtos/create-field.dto.ts
- apps/api/src/domains/admin/channel/field/dtos/replace-field.dto.ts
- apps/api/src/domains/admin/channel/field/dtos/responses/find-fields-response.dto.ts
- apps/api/src/domains/admin/channel/field/field.entity.ts
- apps/api/src/domains/admin/channel/field/field.mysql.service.ts
- apps/api/src/domains/admin/channel/field/field.service.ts
- apps/api/src/domains/admin/feedback/feedback.entity.ts
- apps/api/src/domains/admin/feedback/feedback.mysql.service.ts
- apps/api/src/domains/admin/feedback/feedback.os.service.ts
- apps/api/src/domains/admin/feedback/feedback.service.spec.ts
- apps/api/src/domains/admin/feedback/feedback.service.ts
- apps/api/src/domains/admin/project/webhook/webhook.listener.ts
- apps/api/src/domains/api/feedback.controller.ts
- apps/api/src/domains/operation/migration/migration.service.ts
- apps/api/src/test-utils/fixtures.ts
- apps/web/src/types/field.type.ts
- add field property
- deprecate field type
> feat: field property (READ_ONLY, EDITABLE)

- .github/DISCUSSION_TEMPLATE/ideas.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
> chore: issue and discussion template

- apps/api/src/domains/admin/project/webhook/webhook.service.spec.ts
- apps/api/src/domains/admin/project/webhook/webhook.service.ts
- webhook can be created with same urls
> fix: webhook duplication check

- apps/web/src/containers/setting-menu/RoleSetting/RoleSettingTable.tsx
This fix meets backward compatibility for role changes.
> fix editing role bug

- docker/api.dockerfile
- docker/web.dockerfile
fix turbo version in dockerfile because of turbo version major update
> fix: dockerfile for turbo version

- apps/api/src/common/entities/common.entity.ts
- apps/api/src/domains/admin/history/history.entity.ts
- apps/api/src/domains/admin/history/history.service.ts
- apps/api/src/domains/admin/project/webhook/webhook.listener.ts
- Add log when successfully sent webhook
- Make `UserEntity` referenced by `HistoryEntity` nullable to fix type check error
> feat: add log when successfully sent webhook

- apps/web/public/locales/ko/common.json
- apps/web/src/entities/channel/ui/channel-info-form.ui.tsx
- apps/web/src/entities/channel/ui/image-config-form.ui.tsx
- apps/web/src/widgets/feedback-table/ui/issue-cell/issue-cell.tsx
- apps/web/src/widgets/setting-menu/ui/channel/image-config-setting.ui.tsx
- fix Channel ID Label in Channel Information Setting
- fix Role name kr text
- fix Image URL Domain Whitelist Toggle bug
> fix: minor bugs in web

- .github/workflows/e2e-test.yml
- docker/docker-compose.infra-amd64.yml
- docker/docker-compose.infra-arm64.yml
- renovate.json
- fix mysql version to 8.0.39 (the latest stable version within 8.0.x)
- prevent mysql version to be changed automatically by renovate bot
> fix mysql version to 8.0.39

- apps/api/package.json
- apps/api/src/configs/modules/typeorm-config/migrations/1725935382221-add-order-on-field.ts
- apps/api/src/domains/admin/channel/channel/dtos/requests/create-channel-request.dto.ts
- apps/api/src/domains/admin/channel/field/dtos/create-field.dto.ts
- apps/api/src/domains/admin/channel/field/dtos/replace-field.dto.ts
- apps/api/src/domains/admin/channel/field/dtos/responses/find-fields-response.dto.ts
- apps/api/src/domains/admin/channel/field/field.entity.ts
- apps/api/src/domains/admin/channel/field/field.mysql.service.ts
- add `order` column to `FieldEntity`
> add order column to field entity

- apps/api/src/configs/modules/typeorm-config/migrations/1726022408533-change-fields-key-name-collate.ts
- Change the collation of follwing columns:
- `fields.key`: `utf8mb4_0900_ai_ci` -> `utf8mb4_bin`
- `fields.name`: `utf8mb4_0900_ai_ci` -> `utf8mb4_bin`
> change fields key name collation

- README.md
- Change License Copyright to `Copyright 2024 LY Corporation`
> change copyright

- apps/api/integration-test/test-specs/channel.integration-spec.ts
- apps/api/src/domains/admin/channel/field/field.mysql.service.ts
- add field key restriction
- allow only alphanumeric and underscore
> add field key restriction

- apps/api/src/configs/app.config.ts
- apps/api/src/domains/admin/tenant/tenant.service.ts
- supplement feedback ttl feature
- make sure enableAutoFeedbackDeletion variable be `boolean`
- supplement log to add `autoFeedbackDeletionPeriodDays`
> supplement feedback ttl feature

- apps/api/src/domains/admin/feedback/dtos/generate-excel.dto.ts
- apps/api/src/domains/admin/feedback/feedback.controller.spec.ts
- apps/api/src/domains/admin/feedback/feedback.controller.ts
- apps/api/src/domains/admin/feedback/feedback.service.ts
- apps/api/src/domains/api/api.module.ts
- fix excel download timzone bug
> fix excel download timezone bug

- .github/workflows/integration-test.yml
- renovate.json
- disable renovate for integration test
> disable renovate for integration test

- apps/api/src/domains/admin/tenant/dtos/requests/setup-tenant-request.dto.ts
- apps/api/src/domains/admin/tenant/dtos/setup-tenant.dto.ts
- apps/api/src/domains/admin/tenant/tenant.module.ts
- apps/api/src/domains/admin/tenant/tenant.service.ts
- apps/api/src/domains/admin/user/user.module.ts
- apps/cli/bin/auf-cli.ts
- modify tenant create api
- add email, password parameter on `POST /api/admin/tenants` api
- remove `user@feedback.com` account creation logic
> modify tenant create api

- apps/api/src/domains/admin/project/member/member.service.ts
- do not validate allow domains on tenant creation
> do not validate allow domains on tenant creation

- apps/api/src/domains/admin/auth/auth.controller.ts
- apps/api/src/domains/admin/user/dtos/find-all-users.dto.ts
- apps/api/src/domains/admin/user/dtos/requests/get-all-users-request.dto.ts
- apps/api/src/domains/admin/user/user.service.ts
- extend user search query to allow array
> extend user search query to allow array

- apps/api/src/common/dtos/time-range.dto.ts
- apps/api/src/domains/api/api.module.ts
- apps/api/src/domains/api/project.controller.ts
- add project info api
- add timezone(UTC) to TimeRange
> add project info api

- apps/api/src/common/helper/paginate.helper.ts
- apps/api/src/domains/admin/channel/channel/channel.mysql.service.ts
- apps/api/src/domains/admin/project/issue/issue.service.ts
- apps/api/src/domains/admin/project/project/project.service.ts
- apps/api/src/domains/admin/user/user.service.ts
- fix pagination bug
- there is a bug in `nestjs-typeorm-paginate` library (https://github.com/nestjsx/nestjs-typeorm-paginate/issues/627)
- made a helper to workaround
> fix paginate bug

- apps/api/src/common/helper/paginate.helper.ts
- fix wrong total items count bug
- query builder should be cloned and set find options
> fix wrong total items

- apps/api/integration-test/test-specs/channel.integration-spec.ts
- apps/api/integration-test/test-specs/feedback.integration-spec.ts
- apps/api/integration-test/test-specs/issue.integration-spec.ts
- apps/api/integration-test/test-specs/project.integration-spec.ts
- apps/api/integration-test/test-specs/tenant.integration-spec.ts
- apps/api/src/common/enums/query-v2-conditions.enum.ts
- apps/api/src/domains/admin/feedback/dtos/find-feedbacks-by-channel-id-v2.dto.ts
- apps/api/src/domains/admin/feedback/dtos/generate-excel.dto.ts
- apps/api/src/domains/admin/feedback/dtos/requests/export-feedbacks-request.dto.ts
- apps/api/src/domains/admin/feedback/dtos/requests/find-feedbacks-by-channel-id-request-v2.dto.ts
- apps/api/src/domains/admin/feedback/dtos/scroll-feedbacks-v2.dto.ts
- apps/api/src/domains/admin/feedback/feedback.controller.spec.ts
- apps/api/src/domains/admin/feedback/feedback.controller.ts
- apps/api/src/domains/admin/feedback/feedback.mysql.service.ts
- apps/api/src/domains/admin/feedback/feedback.os.service.ts
- apps/api/src/domains/admin/feedback/feedback.service.ts
- apps/api/src/domains/admin/project/issue/issue.service.spec.ts
- apps/api/src/domains/admin/project/issue/issue.service.ts
- apps/api/src/domains/admin/project/member/member.service.ts
- apps/api/src/domains/admin/tenant/tenant.service.spec.ts
- apps/api/src/domains/admin/user/create-user.service.spec.ts
- apps/api/src/domains/admin/user/create-user.service.ts
- apps/api/src/domains/admin/user/user.service.spec.ts
- apps/api/src/test-utils/providers/tenant.service.providers.ts
- apps/api/src/test-utils/stubs/tenant-repository.stub.ts
- apps/api/src/test-utils/util-functions.ts
- Improved Feedback Search
- Implemented `QueryV2` that allows querying with multiple conditions
- Retained existing `Query(V1)` as it is still used in the external API
- Added V2 DTO and related functions in the controller and service layers
- Modified existing test cases and added new tests
> improve feedback search

- apps/api/src/domains/admin/feedback/dtos/os-query.dto.ts
- apps/api/src/domains/admin/feedback/feedback.mysql.service.ts
- apps/api/src/domains/admin/feedback/feedback.os.service.ts
- Supplemented feedback search functionality
- Made `createdAt` condition as a default condition
- Fixed bug in mysql search
> supplement feedback search

- apps/api/src/domains/admin/project/category/category.controller.ts
- apps/api/src/domains/admin/project/category/category.service.ts
- apps/api/src/domains/admin/project/category/dtos/find-all-categories-by-project-id.dto.ts
- apps/api/src/domains/admin/project/category/dtos/responses/get-all-categories-response.dto.ts
- apps/api/src/domains/admin/project/issue/dtos/responses/find-issue-by-id-response.dto.ts
- apps/api/src/domains/admin/project/issue/issue.service.ts
- apps/api/src/domains/admin/user/user.service.spec.ts
- Added meta data to `GET /api/admin/projects/{projectId}/categories` api
- Added functionality to query `NONE` category by `categoryId: 0`
- Added category info in issue search api
> supplement issue category

- apps/api/src/domains/admin/project/category/category.controller.ts
- apps/api/src/domains/admin/project/category/category.service.ts
- apps/api/src/domains/admin/project/category/dtos/requests/get-all-categories-request.dto.ts
- apps/api/src/domains/admin/project/issue/issue.controller.ts
- apps/api/src/domains/admin/project/issue/issue.entity.ts
- apps/api/src/domains/admin/project/issue/issue.service.ts
- Added delete category api
- `DELETE /admin/projects/:projectId/categories/:categoryId` api
- Added a feature to search by 'categoryName' query
- `GET /admin/projects/:projectId/categories`
- Added a feature to delete a category from an issue
- `DELETE /admin/projects/:projectId/issues/:issueId/category/:categoryId`
> supplement category apis
